[FAB-18281] Add an example for NewApplicationChannelGenesisBlock
hyperledger/fabric-config pull request #42
Opened 2020-10-22 16:23 UTC by satota2

#### Type of change

- Test update
- Documentation update

#### Description

This patch adds an example for NewApplicationChannelGenesisBlock.
This patch also fixes minor typos.

#### Related issues

- https://jira.hyperledger.org/browse/FAB-18281

2020-10-22 16:53 UTC, caod123 requested changes

2020-10-22 16:53 UTC, caod123 commented on configtx/example_test.go
> +			OrdererType: orderer.ConsensusTypeSolo,
As this API will be used almost explicitly for the channel participation API/no system channel case which only supports etcdraft configurations, could you maybe update this example to use `ConsensusTypeEtcdRaft`?

2020-10-22 17:27 UTC, satota2 commented
@caod123 
Thank you for your reviews.

I updated the patch so that the example uses `ConsensusTypeEtcdRaft`.

2020-10-22 18:02 UTC, caod123 approved these changes

2020-10-22 18:05 UTC, caod123 commented
@satota2 looks like github actions is stuck checking the state of the PR, can you force push a no edit amendment to try and retrigger it? `git commit --amend --no-edit`

2020-10-22 18:42 UTC, satota2 commented
@caod123 
I tried to force push the PR. Is this OK?

2020-10-22 22:47 UTC, caod123 approved these changes

2020-10-22 22:47 UTC, caod123 commented
@btl5037 any ideas why this PR is stuck waiting for status report?

2020-10-22 23:58 UTC, btl5037 commented
/azp run

2020-10-23 13:01 UTC, btl5037 commented
/azp run

2020-10-23 13:15 UTC, merged